name: thismed_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get: ^4.6.6
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.1.0
  intl: ^0.19.0
  nil: ^1.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
